### PR TITLE
Require at least 2 pins

### LINKED ISSUE #3: Must require at least two pins, not just one.
To be valid, an HPKP header mush pin : 
- at least one key of the current certificate chain.
- at least one key NOT in the current certificate chain (aka "Backup pin")
So any hpkp header with less than one pin can't be valid

https://tools.ietf.org/html/rfc7469#section-4.3

https://developer.mozilla.org/en-US/docs/Web/Security/Public_Key_Pinning

### PR DESCRIPTION
**Pull request by tdelmas**
Fix #3

### CODE REVIEW

**Comment by EvanHahn** [comment]
Thanks! I'm going to clean this up and then publish a new version.

**Comment by EvanHahn** [comment]
Released `hpkp@0.2.0` and `helmet@0.10.0`.

**Comment by EvanHahn** [comment]
I'm building a list of contributors for a new Helmet.js website. Do you have a name and/or website you want me to use to credit you?

**Comment by tdelmas** [comment]
@EvanHahn Thanks, if you want you can specify my name Tom Delmas

**Comment by EvanHahn** [comment]
Will do! Stay tuned for your name on a new Helmet website.

**Pull request merged**
