### PR TITLE
Require at least 2 Pin : fixes #3

### LINKED ISSUE #3: Must require at least two pins, not just one.
To be valid, an HPKP header mush pin : 
- at least one key of the current certificate chain.
- at least one key NOT in the current certificate chain (aka "Backup pin")
So any hpkp header with less than one pin can't be valid

https://tools.ietf.org/html/rfc7469#section-4.3

https://developer.mozilla.org/en-US/docs/Web/Security/Public_Key_Pinning

### PR DESCRIPTION
**Pull request by tdelmas**

### CODE REVIEW

**Comment by tdelmas** [comment]
If you need some changes before the merge don't hesitate to ask.

**Comment by EvanHahn** [comment]
Could you [squash these into one commit](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) called `Require at least 2 pins`?

**Comment by tdelmas** [comment]
I've successfully squash my commits but I think I messed up something (why I see "Fix link to spec"?...) I'll try clean that tomorrow, sorry, I need read a little more about git rebase !

**Comment by EvanHahn** [comment]
If you'd prefer, I can close this issue and copy your code myself.

**Comment by tdelmas** [comment]
As "Fix link to spec" is already merged to your repo, I don't understand why it's present in this pull request. I think you can simply merge this pull request without problem (but if you want to copy the code manually, you can too). And anyway, I'll spend time tomorrow to try figure it out what happened, I'll keep you posted

**Pull request closed without merging**
